Move platform dependency to Swift Package Manager
kieranb662/SegmentedPicker pull request #1
Opened 2020-04-27 19:08 UTC by kozlowsqi

This moves the platform dependency from code to swift package manager,
meaning the @available clause can be dropped in sources.

2020-04-27 19:30 UTC, kieranb662 requested changes
`DragGesture` not available on TVOS. Other than that great job, Thanks!

2020-04-27 19:30 UTC, kieranb662 commented on Package.swift
> +        .tvOS(.v13)
Drag Gesture not available on tvOS. Other than that, looks good

2020-04-28 09:18 UTC, kozlowsqi commented on Package.swift
> +        .tvOS(.v13)
```suggestion
```

2020-04-28 09:18 UTC, kozlowsqi commented on Package.swift
> +        .tvOS(.v13)
I suggest we remove it then from the supported platforms for now.. 
 Note that the tvOS picker looks like: 

<img width="149" alt="image" src="https://user-images.githubusercontent.com/32329188/80470193-f389df00-8941-11ea-9114-6d095c563ce7.png">

And shouldn't be too hard to support

2020-05-04 11:10 UTC, kozlowsqi commented
this still active?

2020-05-07 20:11 UTC, closed without merging